# Entry
E | vec3(C, C, C)
  ;

# Terminal
B | random
  | x
  | y
  | t
  | abs(x)
  | abs(y)
  | sqrt(add(mul(x, x), mul(y, y))) # Distance from (0, 0) to (x, y)
  ;

# Expressions
C ||  B
  |  E
  ||| add(C, C)
  ||| mul(C, C)
  ||  sqrt(abs(C))
  # ||| abs(C)
  #||| sin(C)
  ;
